README.md
serverless.yml
src/functions/clients.ts
src/functions/users.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/15 の対応を行う。

resolov #15 ユーザー情報を扱うエンドポイントを作成する

---

README.md
src/domain/error-response.ts
src/errors/not-found-error.ts
src/functions/clients.ts
src/functions/users.ts
src/repositories/client-repository.ts
src/repositories/user-repository.ts

resolve #18 findClientで結果が見つからない場合に404を返却する

---

serverless.yml
src/functions/auth.ts

エンドポイントの名前とインアウトを決めるだけ。
本格的な実装は https://github.com/keita-nishimoto/aws-serverless-prototype/issues/28 で行う。

resolve #8 lambdaでカスタム認可用のfunctionを作成する

---

README.md
serverless.yml
src/functions/auth.ts
types.d.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/9

resolve #9 lambdaにカスタム認可を設定する

---

README.md
package.json
src/domain/auth/access-token-entity.ts
src/domain/auth/introspection-response-interface.ts
src/domain/user/user-entity.ts
src/functions/auth.ts
src/repositories/access-token-repository.ts
src/repositories/client-repository.ts
yarn.lock

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/28

resolve #28 CustomAuthorizerの内部実装を行う

---

README.md

#39 READMEの表記ズレを修正

---

src/domain/auth/access-token-entity.ts
src/domain/auth/introspection-response-interface.ts
src/domain/client/client-entity.ts
src/domain/client/client-repository-interface.ts
src/domain/error-response.ts
src/domain/user/user-entity.ts
src/domain/user/user-repository-interface.ts
src/errors/not-found-error.ts
src/functions/auth.ts
src/functions/client.ts
src/functions/user.ts
src/repositories/access-token-repository.ts
src/repositories/client-repository.ts
src/repositories/user-repository.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/35 の対応です。

resolve #35 exportの方法は全体的に"export default"で行うように変更

---

src/domain/auth/access-token-repository-interface.ts
src/factories/aws-sdk-factory.ts
src/functions/auth.ts
src/functions/client.ts
src/functions/user.ts
src/repositories/access-token-repository.ts
src/repositories/client-repository.ts
src/repositories/user-repository.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/22

resolve #22 Repositoryクラスのリファクタリング

---

tsconfig.json

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/56

resolve #56 TypeScriptのbuild高速化

---

src/domain/auth/aws/iam/AuthorizeResponse.ts
src/domain/auth/aws/iam/PolicyDocument.ts
src/domain/auth/aws/iam/Statement.ts
src/functions/auth.ts
src/repositories/ClientRepository.ts
src/repositories/DynamoDbResponse.ts
src/repositories/UserRepository.ts
tsconfig.json

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/46

resolve #46 any型を利用している箇所を可能な限り0にする

---

README.md
serverless.yml
src/domain/auth/aws/iam/AuthorizeResponse.ts
src/domain/auth/aws/iam/PolicyDocument.ts
src/domain/auth/aws/iam/Statement.ts
src/functions/client.ts
src/infrastructures/Environment.ts
src/repositories/ClientRepository.ts
src/repositories/UserRepository.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/7

Feature/issue7 環境変数を指定してデプロイする方法をREADMEに記載する

---

README.md
serverless.yml
src/repositories/AccessTokenRepository.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/37

resolve #37 AuthleteのAPIキー、APIシークレットを環境変数から取得出来るようにする

---

README.md
serverless.yml
src/domain/ErrorResponse.ts
src/domain/auth/PasswordHash.ts
src/domain/auth/PasswordService.ts
src/domain/user/UserEntity.ts
src/errors/UnauthorizedError.ts
src/functions/auth.ts
src/functions/authentication.ts
src/functions/authorization.ts
src/functions/user.ts
src/repositories/DynamoDbResponse.ts
src/repositories/UserRepository.ts
yarn.lock

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/34

resolve #34 認証コールバックエンドポイントの実装

---

serverless.yml
src/domain/auth/AccessTokenEntity.ts
src/domain/resource/ResourceEntity.ts
src/domain/resource/ResourceRepositoryInterface.ts
src/functions/auth.ts
src/functions/resource.ts
src/repositories/DynamoDbResponse.ts
src/repositories/ResourceRepository.ts
yarn.lock

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/64

resolve #64 scopeに応じたAPIを認可させるように処理を追加する

---

serverless.yml
src/domain/auth/AuthleteResponse.ts
src/domain/auth/AuthorizationCodeEntity.ts
src/functions/auth.ts
src/repositories/AuthorizationRepository.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/71

resolve #71 認可エンドポイントの実装（認可コードの発行）

---

README.md

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/76

resolve #76 認可コードの発行方法をREADMEに記載する

---

README.md
serverless.yml
src/domain/auth/AccessTokenEntity.ts
src/domain/auth/AuthleteResponse.ts
src/functions/auth.ts
src/functions/token.ts
src/repositories/AccessTokenRepository.ts
src/repositories/AuthorizationRepository.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/78

resolve #78 認可コードからアクセストークンを発行する

---

README.md
package.json
src/repositories/AccessTokenRepository.ts
yarn.lock

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/69

resolve #69 debuggerでデバック可能な環境を構築する

---

README.md
serverless.yml
src/domain/auth/AuthleteResponse.ts
src/domain/client/ClientEntity.ts
src/domain/client/ClientRepositoryInterface.ts
src/domain/client/ClientRequest.ts
src/functions/client.ts
src/repositories/ClientRepository.ts
src/repositories/DynamoDbResponse.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/80

resolve #80 クライアント登録時にAuthleteにもクライアントIDの登録を行う

---

README.md
src/domain/ErrorResponse.ts
src/domain/auth/AuthleteResponse.ts
src/errors/BadRequestError.ts
src/errors/ForbiddenError.ts
src/errors/InternalServerError.ts
src/functions/auth.ts
src/functions/token.ts
src/repositories/AccessTokenRepository.ts
src/repositories/AuthorizationRepository.ts
src/repositories/DynamoDbResponse.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/85

resolve #85 クライアントIDに対して許可していないスコープが含まれていた場合はエラーコードを返却する

---

README.md
src/domain/auth/AuthleteResponse.ts
src/functions/resource.ts
src/functions/user.ts
src/repositories/AccessTokenRepository.ts
src/repositories/AuthorizationRepository.ts
src/repositories/ResourceRepository.ts
src/repositories/UserRepository.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/25

resolve #25 予期せぬ例外が起こった際に500を返却するように対応を行う

---

src/domain/SuccessResponse.ts
src/functions/auth.ts
src/functions/client.ts
src/functions/resource.ts
src/functions/token.ts
src/functions/user.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/23

resolve #23 responseの生成ロジックを別クラスに分離する

---

src/config/Authlete.ts
src/infrastructures/Environment.ts
src/repositories/AccessTokenRepository.ts
src/repositories/AuthorizationRepository.ts
src/repositories/ClientRepository.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/74

resolve #74 Authleteの環境変数取得ロジックを共通化する

---

README.md
src/domain/auth/AccessTokenEntity.ts
src/domain/auth/AuthleteResponse.ts
src/domain/auth/PasswordHash.ts
src/functions/auth.ts
src/functions/client.ts
src/functions/resource.ts
src/functions/token.ts
src/functions/user.ts
src/repositories/AccessTokenRepository.ts
src/repositories/ClientRepository.ts
src/repositories/ResourceRepository.ts
tsconfig.json

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/41

resolve #41 tsconfig.jsonの設定見直し

---

README.md
package.json
paths.js
src/repositories/AuthorizationRepository.ts
src/repositories/DynamoDbResponse.ts
tslint.json
webpack.config.js

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/14

resolve #14 tslint.jsonの設定を変更

---

src/domain/auth/AuthleteResponse.ts
src/domain/auth/aws/iam/PolicyDocument.ts
src/repositories/UserRepository.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/67

resolve #67 AWS SDKの非同期通信箇所をPromiseを使った形に変更する

---

src/domain/auth/AccessTokenEntity.ts
src/functions/auth.ts
src/tests/integration/functions/auth/Authorization.test.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/89

resolve #89 auth.hasRequiredScopesのリファクタリング

---

package.json
src/domain/client/ClientValidationService.ts
src/domain/client/request/ClientRequest.ts
src/domain/resource/request/ResourceRequest.ts
src/domain/user/request/UserRequest.ts
src/functions/auth.ts
src/functions/client.ts
src/functions/resource.ts
src/functions/token.ts
src/functions/user.ts
src/infrastructures/Environment.ts
src/types/aws/types.d.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/114

resolve #114 各lambda関数のeventはAPIGatewayEventを使うように変更

---

config/tests/webpack.config.js
paths.js
src/domain/user/UserValidationService.ts
src/functions/user.ts
src/tests/integration/functions/user/Create.test.ts
src/tests/unit/domain/user/UserValidationService/CreateValidate.test.ts

add UserValidationService

---

src/factories/RequestFactory.ts
src/functions/auth.ts
src/functions/resource.ts
src/functions/token.ts
src/functions/user.ts
src/types/aws/types.d.ts

作成した機能を使って各lambda functionも置き換え。

lambdaEventからbodyを抽出する機能を作成

---

src/domain/user/UserEntity.ts
src/domain/user/UserRepositoryInterface.ts
src/functions/auth.ts
src/functions/user.ts
src/repositories/UserRepository.ts
src/tests/integration/functions/auth/Authentication.test.ts
src/tests/integration/functions/user/Create.test.ts
src/tests/integration/functions/user/FindUser.test.ts

ついでにuserIdという名称もsubjectに統一。（Authleteの物理名に合わせて）

UserEntityをBuilderPatternを用いてimmutableな形に変更

---

src/domain/auth/AccessTokenEntity.ts
src/domain/auth/AccessTokenRepositoryInterface.ts
src/domain/client/ClientEntity.ts
src/domain/client/ClientRepositoryInterface.ts
src/domain/resource/ResourceEntity.ts
src/domain/resource/ResourceRepositoryInterface.ts
src/functions/auth.ts
src/functions/client.ts
src/functions/resource.ts
src/repositories/AccessTokenRepository.ts
src/repositories/ClientRepository.ts
src/repositories/ResourceRepository.ts
src/tests/integration/functions/auth/Authentication.test.ts
src/tests/integration/functions/resource/Create.test.ts
src/tests/integration/functions/resource/Find.test.ts
src/tests/integration/functions/user/FindUser.test.ts
src/tests/unit/repositories/AccessTokenRepository/Fetch.test.ts
src/types/authlete/types.d.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/pull/137 で行った内容を全体的に適応。

全てのEntityクラスをimmutableに変更

---

src/factories/AuthleteHttpClientFactory.ts
src/functions/auth.ts
src/functions/resource.ts
src/functions/token.ts
src/functions/user.ts
src/repositories/AccessTokenRepository.ts
src/tests/integration/functions/auth/Authentication.test.ts
src/tests/integration/functions/user/FindUser.test.ts
src/tests/lib/TestUtil.ts
src/tests/unit/repositories/AccessTokenRepository/Fetch.test.ts
src/tests/unit/repositories/AccessTokenRepository/Issue.test.ts

表題の通り。
AccessTokenRepositoryのテストをmockを使って書く事が可能になった。

AccessTokenRepositoryで使っているaxiosを外から渡す形に変更する

---

serverless.yml
tsconfig.json

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/146

resolve #146 Update the Node.js version to 6.10.0

---

README.md
package.json

resolve #145 Update the node-inspector version to 1.0.0

---

src/domain/auth/AuthorizationCodeEntity.ts
src/domain/auth/AuthorizationRepositoryInterface.ts
src/repositories/AuthorizationRepository.ts

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/144

resolve #144 AuthorizationCodeEntityの作成方法を他にEntityに合わせる

---

package.json
serverless.yml
yarn.lock

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/165

resolve #165 AWS上で実際に利用しないnpmパッケージはdevDependenciesに登録するように変更

---

package.json
yarn.lock

https://github.com/keita-nishimoto/aws-serverless-prototype/issues/167

resolve #167 Local Debugging を node-inspectorを使わない方法に変更する
